In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/Users/HP/Desktop/fivethirtyeight/data/police-deaths/all_data police death.csv',encoding = "ISO-8859-1")

In [3]:
data.head()

,person,dept,eow,cause
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire
2,Deputy Sheriff Isaac Smith,"Westchester County Sheriff's Department, NY","EOW: Thursday, May 17, 1792",Cause of Death: Gunfire
3,Marshal Robert Forsyth,United States Department of Justice - United S...,"EOW: Saturday, January 11, 1794",Cause of Death: Gunfire
4,Sheriff Robert Maxwell,"Greenville County Sheriff's Office, SC","EOW: Sunday, November 12, 1797",Cause of Death: Gunfire

In [4]:
data.head(2)

,person,dept,eow,cause
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire

In [5]:
data['NAME'] = data['person']

In [6]:
data['DESIGNATION'] = data['person'].apply(lambda x:x.split(' ')[0])

In [7]:
data.head(2)

,person,dept,eow,cause,NAME,DESIGNATION
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff

In [8]:
data['DEPARTMENT'] = data['dept'].apply(lambda x:x.split(',')[0])

In [9]:
data.head(2)

,person,dept,eow,cause,NAME,DESIGNATION,DEPARTMENT
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office

In [10]:
data['STATE'] = data['dept'].apply(lambda x:x.split(',')[-1])

In [11]:
data.head(2)

,person,dept,eow,cause,NAME,DESIGNATION,DEPARTMENT,STATE
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY

In [12]:
data['YEAR'] = data['eow'].apply(lambda x:x.split(',')[-1])

In [13]:
data.head(2)

,person,dept,eow,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791

In [14]:
data['month'] = data['eow'].apply(lambda x:x.split(',')[1])

In [15]:
data['MONTH'] = data['month'].apply(lambda x:x.split(' ')[1])

In [16]:
data.head(2)

,person,dept,eow,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,month,MONTH
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January 3,January
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October 22,October

In [17]:
data['DATE'] = data['month'].apply(lambda x:x.split(' ')[2])

In [18]:
data.head(2)

,person,dept,eow,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,month,MONTH,DATE
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January 3,January,3
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October 22,October,22

In [19]:
del data['month']

In [20]:
del data['person']

In [21]:
del data['dept']

In [22]:
data.head(2)

,eow,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,MONTH,DATE
0,"EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January,3
1,"EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October,22

In [23]:
data['day'] = data['eow'].apply(lambda x:x.split(',')[0])

In [24]:
data.head(2)

,eow,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,MONTH,DATE,day
0,"EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January,3,EOW: Monday
1,"EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October,22,EOW: Saturday

In [25]:
data['DAY'] = data['day'].apply(lambda x:x.split(':')[1])

In [26]:
data.head(2)

,eow,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,MONTH,DATE,day,DAY
0,"EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January,3,EOW: Monday,Monday
1,"EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October,22,EOW: Saturday,Saturday

In [27]:
del data['day']

In [28]:
data.head(2)

,eow,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,MONTH,DATE,DAY
0,"EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January,3,Monday
1,"EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October,22,Saturday

In [29]:
del data['eow']

In [30]:
data.head(2)

,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,MONTH,DATE,DAY
0,Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January,3,Monday
1,Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October,22,Saturday

In [31]:
data['CAUSE'] = data['cause'].apply(lambda x:x.split(':')[-1])

In [32]:
data.head()

,cause,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,MONTH,DATE,DAY,CAUSE
0,Cause of Death: Gunfire,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January,3,Monday,Gunfire
1,Cause of Death: Gunfire,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October,22,Saturday,Gunfire
2,Cause of Death: Gunfire,Deputy Sheriff Isaac Smith,Deputy,Westchester County Sheriff's Department,NY,1792,May,17,Thursday,Gunfire
3,Cause of Death: Gunfire,Marshal Robert Forsyth,Marshal,United States Department of Justice - United S...,US,1794,January,11,Saturday,Gunfire
4,Cause of Death: Gunfire,Sheriff Robert Maxwell,Sheriff,Greenville County Sheriff's Office,SC,1797,November,12,Sunday,Gunfire

In [33]:
del data['cause']

In [34]:
data.head(25)

,NAME,DESIGNATION,DEPARTMENT,STATE,YEAR,MONTH,DATE,DAY,CAUSE
0,Constable Darius Quimby,Constable,Albany County Constable's Office,NY,1791,January,3,Monday,Gunfire
1,Sheriff Cornelius Hogeboom,Sheriff,Columbia County Sheriff's Office,NY,1791,October,22,Saturday,Gunfire
2,Deputy Sheriff Isaac Smith,Deputy,Westchester County Sheriff's Department,NY,1792,May,17,Thursday,Gunfire
3,Marshal Robert Forsyth,Marshal,United States Department of Justice - United S...,US,1794,January,11,Saturday,Gunfire
4,Sheriff Robert Maxwell,Sheriff,Greenville County Sheriff's Office,SC,1797,November,12,Sunday,Gunfire
5,High Sheriff John Caldwell Cook,High,Mecklenburg County Sheriff's Office,NC,1804,October,16,Tuesday,Gunfire
6,Watchman Christian Luswanger,Watchman,New York City Watch,NY,1806,December,25,Thursday,Stabbed
7,Deputy Sheriff John A. Gooch,Deputy,Livingston County Sheriff's Department,KY,1807,March,7,Saturday,Gunfire
8,Deputy Sheriff Ebenezer Parker,Deputy,Cumberland County Sheriff's Office,ME,1808,January,18,Monday,Assault
9,Night Watchman George Workner,Night,Baltimore City Police Department,MD,1808,March,15,Tuesday,Stabbed
10,Boatman Asa Marsh,Boatman,United States Department of the Treasury - Cus...,US,1808,August,3,Wednesday,Gunfire
11,Boatman Ellis Drake,Boatman,United States Department of the Treasury - Cus...,US,1808,August,3,Wednesday,Gunfire
12,Custom House Officer Daniel Miller,Custom,United States Department of the Treasury - Cus...,US,1810,January,1,Monday,Gunfire
13,Deputy Sheriff John Tileston Downes,Deputy,Hancock County Sheriff's Department,ME,1811,January,28,Monday,Gunfire
14,Customs Inspector John Stout,Customs,United States Department of the Treasury - Cus...,US,1814,January,21,Friday,Gunfire
15,Sheriff John Coor Pender,Sheriff,Wayne County Sheriff's Office,NC,1816,January,1,Monday,Gunfire
16,Sheriff Caleb Hewitt,Sheriff,Davidson County Sheriff's Office,TN,1816,September,9,Monday,Assault
17,Deputy Sheriff William Huddleston,Deputy,Schoharie County Sheriff's Department,NY,1818,October,9,Friday,Assault
18,"Constable Jacob Dearduff, Sr.",Constable,Jamestown Police Department,OH,1823,February,22,Saturday,Stabbed
19,Constable Elijah Chenault,Constable,Alexandria Police Department,VA,1823,August,4,Monday,Assault
20,Constable Robert Murphy,Constable,Franklin County Sheriff's Department,IN,1824,November,11,Thursday,Stabbed
21,Constable William Davidson,Constable,Pennsylvania State Constable - Venango County,PA,1825,April,14,Thursday,Gunfire
22,Watch Officer Jonathan Houghton,Watch,Boston Watch,MA,1825,December,19,Monday,Assault
23,Watchman Gerrard Arnold,Watchman,Alexandria Police Department,VA,1827,September,9,Sunday,Assault
24,Watchman Steven Heimer,Watchman,Philadelphia Police Department,PA,1828,January,8,Tuesday,Gunfire

In [35]:
data.isnull().sum()

NAME           0
DESIGNATION    0
DEPARTMENT     0
STATE          0
YEAR           0
MONTH          0
DATE           0
DAY            0
CAUSE          0
dtype: int64

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22800 entries, 0 to 22799
Data columns (total 9 columns):
NAME           22800 non-null object
DESIGNATION    22800 non-null object
DEPARTMENT     22800 non-null object
STATE          22800 non-null object
YEAR           22800 non-null object
MONTH          22800 non-null object
DATE           22800 non-null object
DAY            22800 non-null object
CAUSE          22800 non-null object
dtypes: object(9)
memory usage: 1.6+ MB

In [37]:
data['DATE'] = data['DATE'].astype(int)

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22800 entries, 0 to 22799
Data columns (total 9 columns):
NAME           22800 non-null object
DESIGNATION    22800 non-null object
DEPARTMENT     22800 non-null object
STATE          22800 non-null object
YEAR           22800 non-null object
MONTH          22800 non-null object
DATE           22800 non-null int64
DAY            22800 non-null object
CAUSE          22800 non-null object
dtypes: int64(1), object(8)
memory usage: 1.6+ MB

In [39]:
data.to_csv('fairco')

In [40]:
data['YEAR'].value_counts()

 1930    323
 1927    305
 1932    301
 1931    296
 1924    289
 1921    287
 1929    286
 1974    281
 1973    277
 1925    276
 1928    275
 1922    264
 1926    258
 1934    256
 1971    251
 1923    251
 1975    247
 2001    247
 1933    244
 1919    243
 1935    238
 1972    237
 1970    231
 1920    224
 1979    223
 1978    217
 1980    213
 2007    213
 1936    210
 1937    205
        ...
 1844      4
 1849      4
 1808      4
 1841      4
 1843      3
 1847      3
 1791      2
 1834      2
 1825      2
 1840      2
 1823      2
 1816      2
 1811      1
 1794      1
 1824      1
 1827      1
 1806      1
 1810      1
 1814      1
 1848      1
 1832      1
 1842      1
 1833      1
 1807      1
 1828      1
 1830      1
 1797      1
 1804      1
 1818      1
 1792      1
Name: YEAR, Length: 202, dtype: int64